[package]
authors = ["Jason Ozias <jason.ozias@gmail.com>"]
name = "twist"
version = "0.1.0"

[[bin]]
name = "twists"
path = "src/server/main.rs"

[[bin]]
name = "twisty"
path = "src/client/main.rs"

[[bin]]
name = "twister"
path = "src/tls_client/main.rs"

[dependencies]
base64 = "0.3.0"
byteorder = "1.0.0"
clap = "2.20.3"
env_logger = "0.4.0"
futures = "0.1.10"
httparse = "1.2.1"
native-tls = "0.1.1"
sha1 = "0.2.0"
slog-term = "1.4.0"
tokio-core = "0.1.4"
tokio-proto = "0.1.0"
tokio-service = "0.1.0"

[dependencies.slog]
features = ["max_level_trace", "release_max_level_trace"]
version = "1.4.1"

[dependencies.tokio-tls]
features = ["tokio-proto"]
version = "0.1.1"

[lib]
name = "twist"
path = "src/lib.rs"
