[package]
name = "soketto"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>", "Jason Ozias <jason.g.ozias@gmail.com>"]
description = "A websocket protocol implementation as as set of tokio codecs."
keywords = ["tokio", "websocket", "codec"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/paritytech/soketto"
edition = "2018"

[dependencies]
base64 = "0.10.1"
bytes = "0.4.12"
futures = "0.1.26"
http = "0.1.17"
httparse = "1.3.3"
log = "0.4.6"
rand = "0.6.5"
sha1 = "0.6.0"
smallvec = "0.6.9"
tokio-codec = "0.1.1"
tokio-io = "0.1.12"

[dev-dependencies]
env_logger = "0.6.1"
tokio = "0.1.20"
