[package]
authors = ["Jason Ozias <jason.ozias@gmail.com>"]
name = "twist"
version = "0.1.0"

[lib]
name = "twist"
path = "src/lib.rs"

[[bin]]
name = "twist-srv"
path = "src/server/main.rs"

[[bin]]
name = "twist-cl"
path = "src/client/main.rs"

[dependencies]
byteorder = "1.0.0"
clap = "2.20.1"
futures = "0.1.9"
slog-term = "1.4.0"
tokio-core = "0.1.4"
tokio-service = "0.1.0"

[dependencies.slog]
version = "1.4.1"
features = ["max_level_trace", "release_max_level_trace"]

[dependencies.tokio-proto]
branch = "stream-complete-with-chunk"
git = "https://github.com/rustyhorde/tokio-proto.git"
