[package]
name = "twist"
version = "0.1.1"
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
description = "tokio base websocket server"
documentation = "https://github.com/rustyhorde/twist"
homepage = "https://github.com/rustyhorde/twist"
repository = "https://github.com/rustyhorde/twist"
readme = "README.md"
license = "MIT"
keywords = ["tokio","websocket"]

[dependencies]
base64 = "0.3.0"
byteorder = "1.0.0"
futures = "0.1.10"
httparse = "1.2.1"
sha1 = "0.2.0"
tokio-core = "0.1.4"
tokio-proto = "0.1.0"

[dependencies.slog]
features = ["max_level_trace", "release_max_level_trace"]
version = "1.4.1"

[lib]
name = "twist"
path = "src/lib.rs"
