[package]
name = "soketto"
version = "0.3.0"
authors = ["Parity Technologies <admin@parity.io>", "Jason Ozias <jason.g.ozias@gmail.com>"]
description = "A websocket protocol implementation as as set of tokio codecs."
keywords = ["tokio", "websocket", "codec"]
license = "Apache-2.0 OR MIT"
readme = "README.md"
repository = "https://github.com/paritytech/soketto"
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[features]
deflate = ["flate2"]
# This feature enables the use of uninitialised memory for the deflate
# extension. When compressing or decompressing, an uninitialised byte
# slice will be used for writing the resulting bytes, assuming that
# flate2 really only writes to and does not read from this memory.
deflate_with_uninitialised_memory = []

[dependencies]
base64 = "0.10.1"
bytes = "0.4.12"
flate2 = { version = "1.0.11", features = ["zlib"], default-features = false, optional = true }
futures-preview = "0.3.0-alpha.18"
http = "0.1.18"
httparse = "1.3.4"
log = "0.4.8"
rand = "0.7.2"
sha1 = "0.6.0"
smallvec = "0.6.10"
tokio-codec = "0.2.0-alpha.5"
tokio-io = "0.2.0-alpha.5"

[dev-dependencies]
assert_matches = "1.3.0"
async-std = "0.99.8"
env_logger = "0.7.0"
quickcheck = "0.9.0"
