[package]
authors = ["Jason Ozias <jason.ozias@gmail.com>"]
name = "twist"
version = "0.1.0"

[[bin]]
name = "twist"
path = "src/main.rs"

[[bin]]
name = "twist-cl"
path = "src/client/main.rs"

[dependencies]
byteorder = "1.0.0"
clap = "2.20.1"
env_logger = "0.4.0"
futures = "0.1.9"
slog = "1.4.1"
slog-envlogger = "0.5.0"
slog-stdlog = "1.1.0"
slog-term = "1.4.0"
tokio-core = "0.1.4"
tokio-service = "0.1.0"

[dependencies.tokio-proto]
branch = "stream-complete-with-chunk"
git = "https://github.com/rustyhorde/tokio-proto.git"
