[package]
name = "twist"
version = "0.7.1"
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
description = "An implementation of the RFC6455 websocket protocol as a tokio codec."
documentation = "https://docs.rs/twist"
homepage = "https://rustyhorde.github.io/twist/"
keywords = ["tokio", "websocket", "codec", "serverproto"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rustyhorde/twist"
edition = "2018"

[dependencies]
base64 = "0.10.1"
bytes = "0.4.12"
futures = "0.1.26"
http = "0.1.17"
httparse = "1.3.3"
log = "0.4.6"
rand = "0.6.5"
sha1 = "0.6.0"
smallvec = "0.6.9"
tokio-codec = "0.1.1"
unicase = "2.4.0"

